import React, { createContext, useContext, useState, ReactNode, useEffect } from 'react';

export type Language = 'hindi' | 'english';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation data
const translations = {
  hindi: {
    // Header
    'header.agrisathi': 'AgriSaathi',
    'header.language.hindi': 'हिं',
    'header.language.english': 'EN',

    // Navigation
    'nav.home': 'होम',
    'nav.scan': 'स्कैन',
    'nav.community': 'समुदाय',
    'nav.chat': 'चैट',
    'nav.wallet': 'वॉलेट',
    'nav.profile': 'प्रोफाइल',

    // Dashboard
    'dashboard.welcome': 'स्वागत है, किसान भाई!',
    'dashboard.subtitle': 'आधुनिक तकनीक के साथ बेहतर खेती',
    'dashboard.quickActions': 'त्वरित कार्य',
    'dashboard.weather': 'आज का मौसम',
    'dashboard.cropRecommendations': 'फसल सुझाव',

    // Quick Actions
    'quickActions.scanCrop': 'फसल स्कैन करें',
    'quickActions.scanDescription': 'बीमारी की पहचान',
    'quickActions.voiceAsk': 'आवाज में पूछें',
    'quickActions.voiceDescription': 'स्वरबद्ध सहायक',
    'quickActions.expertChat': 'विशेषज्ञ चैट',
    'quickActions.expertDescription': 'तुरंत सलाह पाएं',
    'quickActions.weather': 'मौसम जानकारी',
    'quickActions.weatherDescription': 'आज का पूर्वानुमान',
    'quickActions.agriCreds': 'AgriCreds',
    'quickActions.earnMore': 'समुदाय में योगदान करके और अधिक कमाएं!',

    // Weather
    'weather.today': 'आज का मौसम',
    'weather.humidity': 'नमी',
    'weather.wind': 'हवा',
    'weather.uvIndex': 'UV Index',
    'weather.rainChance': 'बारिश की संभावना',

    // Crop Recommendations
    'crops.recommendations': 'फसल सुझाव',
    'crops.season': 'सीजन',
    'crops.profitability': 'लाभ',
    'crops.high': 'उच्च',
    'crops.medium': 'मध्यम',
    'crops.low': 'कम',
    'crops.yield': 'उत्पादन',
    'crops.sowing': 'बुआई',
    'crops.marketRate': 'बाजार दर',
    'crops.viewDetails': 'विस्तार देखें',
    'crops.alerts': 'चेतावनी',

    // Crops
    'crops.tomato': 'टमाटर',
    'crops.wheat': 'गेहूं',
    'crops.season.rabi': 'रबी',
    'crops.season.kharif': 'खरीफ',
    'crops.profitability.high': 'उच्च',
    'crops.profitability.medium': 'मध्यम',
    'crops.profitability.low': 'कम',
    'crops.yield.ton_per_hectare': 'टन/हेक्टेयर',
    'crops.yield.qtl_per_hectare': 'क्विंटल/हेक्टेयर',
    'crops.market_unit.kg': 'किग्रा',
    'crops.market_unit.qtl': 'क्विंटल',
    'crops.sowing.oct_nov': 'अक्टूबर-नवंबर',
    'crops.sowing.nov_dec': 'नवंबर-दिसंबर',
    // Alerts
    'alerts.tomato_pest': 'टमाटर में कीट प्रकोप की चेतावनी - तुरंत उपचार करें',
    'alerts.irrigation_needed': 'सिंचाई की जरूरत - मिट्टी की नमी कम है',

    // Disease Detection
    'disease.title': 'फसल स्कैन करें',
    'disease.uploadPhoto': 'फसल की फोटो अपलोड करें',
    'disease.uploadDescription': 'पत्तियों, फूलों या फलों की स्पष्ट तस्वीर लें',
    'disease.gallery': 'गैलरी से चुनें',
    'disease.camera': 'कैमरा खोलें',
    'disease.uploadedPhoto': 'अपलोड की गई फोटो',
    'disease.startAnalysis': 'AI विश्लेषण शुरू करें',
    'disease.analyzing': 'AI विश्लेषण चल रहा है...',
    'disease.pleaseWait': 'कृपया प्रतीक्षा करें',
    'disease.confidence': 'आत्मविश्वास',
    'disease.severity': 'गंभीरता',
    'disease.immediateActions': 'तुरंत करने योग्य उपाय',
    'disease.futurePrevention': 'भविष्य में बचाव',
    'disease.contactExpert': 'विशेषज्ञ से संपर्क करें',
    'disease.buyMedicine': 'दवाई खरीदें',
    'disease.tips': 'बेहतर परिणाम के लिए टिप्स',
    'disease.tip1': 'प्राकृतिक रोशनी में फोटो लें',
    'disease.tip2': 'पत्ती को पास से फोकस करें',
    'disease.tip3': 'साफ़ और स्पष्ट तस्वीर लें',
    'disease.tip4': 'एक से अधिक कोण से फोटो लें',
    'disease.selectCrop': 'फसल का प्रकार चुनें (वैकल्पिक)',
    'disease.autoDetect': 'स्वचालित पहचान',
    'disease.uploadError': 'छवि प्रोसेस करने में विफल',
    'disease.invalidFileType': 'कृपया एक वैध छवि फ़ाइल चुनें',
    'disease.fileTooLarge': 'फ़ाइल का आकार 10MB से कम होना चाहिए',
    'disease.imageUploaded': 'छवि अपलोड की गई',
    'disease.imageReadyForAnalysis': 'छवि विश्लेषण के लिए तैयार है',
    'disease.supportedFormats': 'समर्थित: JPG, PNG, WebP (अधिकतम 10MB)',
    'disease.cameraDescription': 'सीधे फोटो लें',
    'disease.analysisComplete': 'विश्लेषण पूरा',
    'disease.analysisError': 'छवि का विश्लेषण करने में विफल। कृपया पुनः प्रयास करें।',
    'disease.recentAnalyses': 'हाल के विश्लेषण',
    'disease.dragDropText': 'यहां छवि खींचें और छोड़ें, या ब्राउज़ करने के लिए क्लिक करें',
    'disease.browseFiles': 'फ़ाइलें ब्राउज़ करें',

    // Chat
    'chat.title': 'AI चैट सहायक',
    'chat.expertBanner': 'विशेषज्ञ सलाह चाहिए?',
    'chat.expertSubtitle': 'प्रमाणित कृषि विशेषज्ञों से बात करें',
    'chat.call': 'कॉल करें',
    'chat.availableExperts': 'उपलब्ध विशेषज्ञ',
    'chat.chat': 'चैट',
    'chat.nextAvailable': 'अगली बार',
    'chat.voiceListening': 'सुन रहा हूं...',
    'chat.speakQuestion': 'अपना सवाल बोलें',
    'chat.writeQuestion': 'अपना सवाल लिखें...',
    'chat.commonQuestions': 'आम सवाल',
    'chat.weatherInfo': 'मौसम की जानकारी',
    'chat.fertilizerAmount': 'खाद की मात्रा',
    'chat.seedTreatment': 'बीज उपचार',
    'chat.irrigationTime': 'सिंचाई का समय',
    'chat.placeholder': 'अपना संदेश लिखें...',
    'chat.typing': 'टाइप कर रहा है...',
    'chat.clear': 'साफ़ करें',
    'chat.cleared': 'चैट साफ़ की गई',
    'chat.startNewConversation': 'नई बातचीत शुरू करें',
    'chat.responseReceived': 'जवाब मिला',
    'chat.usingRealData': 'वास्तविक कृषि डेटा का उपयोग',
    'chat.usingMockData': 'मॉक डेटा का उपयोग',
    'chat.apiError': 'API त्रुटि',
    'chat.error': 'जवाब प्राप्त करने में विफल',

    // Community
    'community.title': 'समुदाय मंच',
    'community.searchPosts': 'पोस्ट खोजें...',
    'community.post': 'पोस्ट',
    'community.newPost': 'नई पोस्ट लिखें',
    'community.category': 'श्रेणी',
    'community.writeQuestion': 'अपना सवाल या सुझाव लिखें...',
    'community.addPhoto': 'फोटो जोड़ें',
    'community.postNow': 'पोस्ट करें',
    'community.share': 'साझा करें',
    'community.problem': 'समस्या',
    'community.tips': 'टिप्स',
    'community.experience': 'अनुभव',
    'community.market': 'बाजार',

    // Community categories
    'community.category.problem': 'समस्या',
    'community.category.tips': 'टिप्स',
    'community.category.experience': 'अनुभव',
    'community.category.market': 'बाजार',

    // Additional Community translations
    'community.allCategories': 'सभी श्रेणियां',
    'community.loadingPosts': 'पोस्ट लोड हो रही हैं...',
    'community.noPosts': 'कोई पोस्ट नहीं मिली',
    'community.categoryNoPosts': 'श्रेणी में कोई पोस्ट नहीं मिली',
    'community.posting': 'पोस्ट हो रही है...',
    'common.refresh': 'रिफ्रेश',

    // Voice recognition translations
    'voice.listening': 'सुन रहा हूं...',
    'voice.speakNow': 'अपना सवाल बोलें',
    'voice.detected': 'आवाज पहचानी गई',
    'voice.error': 'आवाज त्रुटि',
    'voice.notSupported': 'आवाज समर्थित नहीं',
    'voice.browserSupport': 'आपका ब्राउज़र आवाज पहचान का समर्थन नहीं करता',
    'voice.startFailed': 'आवाज पहचान शुरू नहीं हो सकी',
    'voice.noInput': 'कोई इनपुट नहीं',
    'voice.inputReceived': 'आवाज इनपुट प्राप्त हुआ',

    // Profile
    'profile.title': 'मेरी प्रोफाइल',
    'profile.farmingInfo': 'खेती की जानकारी',
    'profile.landSize': 'भूमि का आकार',
    'profile.experience': 'अनुभव',
    'profile.memberSince': 'सदस्य बने',
    'profile.language': 'भाषा',
    'profile.mainCrops': 'मुख्य फसलें',
    'profile.activityStats': 'गतिविधि सांख्यिकी',
    'profile.postsShared': 'पोस्ट साझा की',
    'profile.helpfulAnswers': 'सहायक उत्तर',
    'profile.questionsAsked': 'प्रश्न पूछे',
    'profile.creditsEarned': 'Credits कमाए',

    // Wallet
    'wallet.title': 'वॉलेट',
    'wallet.connect': 'वॉलेट कनेक्ट करें',
    'wallet.disconnect': 'वॉलेट डिस्कनेक्ट',
    'wallet.overview': 'अवलोकन',
    'wallet.send': 'भेजें',
    'wallet.buy': 'खरीदें',
    'wallet.sell': 'बेचें',
    'wallet.history': 'इतिहास',
    'wallet.balance': 'बैलेंस',
    'wallet.address': 'वॉलेट पता',
    'wallet.copied': 'कॉपी हो गया',
    'wallet.addressCopied': 'पता क्लिपबोर्ड पर कॉपी हो गया है',
    'wallet.sendAgriCreds': 'AgriCreds भेजें',
    'wallet.buyAgriCreds': 'AgriCreds खरीदें',
    'wallet.sellAgriCreds': 'AgriCreds बेचें',
    'wallet.recipientAddress': 'प्राप्तकर्ता का पता',
    'wallet.amount': 'राशि',
    'wallet.numberOfAgriCreds': 'AgriCreds की संख्या',
    'wallet.ethRequired': 'आवश्यक ETH',
    'wallet.ethReceived': 'प्राप्त ETH',
    'wallet.transactionHistory': 'लेन-देन इतिहास',
    'wallet.prices': 'कीमतें',
    'wallet.security': 'सुरक्षा',
    'wallet.walletSecure': 'वॉलेट सुरक्षित है',
    'wallet.metamaskNotFound': 'MetaMask नहीं मिला',
    'wallet.installMetamask': 'कृपया MetaMask इंस्टॉल करें और पेज को रिफ्रेश करें',
    'wallet.walletConnected': 'वॉलेट कनेक्ट हो गया',
    'wallet.walletConnectedSuccess': 'आपका MetaMask वॉलेट सफलतापूर्वक कनेक्ट हो गया है',
    'wallet.connectionFailed': 'कनेक्शन विफल',
    'wallet.walletDisconnected': 'वॉलेट डिस्कनेक्ट',
    'wallet.walletDisconnectedSuccess': 'आपका वॉलेट डिस्कनेक्ट हो गया है',
    'wallet.insufficientBalance': 'अपर्याप्त बैलेंस',
    'wallet.notEnoughAgriCreds': 'आपके पास पर्याप्त AgriCreds नहीं हैं',
    'wallet.insufficientEth': 'अपर्याप्त ETH',
    'wallet.needEth': 'आपको {amount} ETH की आवश्यकता है',
    'wallet.agriCredsSent': 'AgriCreds भेजे गए',
    'wallet.agriCredsSentSuccess': '{amount} AgriCreds सफलतापूर्वक भेजे गए',
    'wallet.agriCredsPurchased': 'AgriCreds खरीदे गए',
    'wallet.agriCredsPurchasedSuccess': '{amount} AgriCreds सफलतापूर्वक खरीदे गए',
    'wallet.agriCredsSold': 'AgriCreds बेचे गए',
    'wallet.agriCredsSoldSuccess': '{amount} AgriCreds सफलतापूर्वक बेचे गए',
    'wallet.transactionFailed': 'लेन-देन विफल',
    'wallet.purchaseFailed': 'खरीद विफल',
    'wallet.saleFailed': 'बिक्री विफल',
    'wallet.invalidAmount': 'अमान्य राशि',
    'wallet.enterValidAmount': 'कृपया एक वैध राशि दर्ज करें',
    'wallet.invalidAddress': 'अमान्य पता',
    'wallet.enterValidAddress': 'कृपया एक वैध Ethereum पता दर्ज करें',
    'wallet.walletNotConnected': 'वॉलेट कनेक्ट नहीं',
    'wallet.connectWalletFirst': 'कृपया पहले अपना वॉलेट कनेक्ट करें',
    'wallet.sending': 'भेज रहा है...',
    'wallet.buying': 'खरीद रहा है...',
    'wallet.selling': 'बेच रहा है...',
    'wallet.connecting': 'कनेक्ट हो रहा है...',
    'wallet.connectMetamask': 'MetaMask से कनेक्ट करें',
    'wallet.manageAgriCreds': 'अपने AgriCreds को प्रबंधित करने के लिए MetaMask से कनेक्ट करें',
    'profile.achievements': 'उपलब्धियां',
    'profile.settings': 'सेटिंग्स',
    'profile.changeLanguage': 'भाषा बदलें',
    'profile.redeemCredits': 'AgriCreds रिडीम करें',
    'profile.insufficientCredits': 'अपर्याप्त क्रेडिट',
    'profile.need50Credits': 'विशेषज्ञों से बात करने के लिए कम से कम 50 AgriCreds की आवश्यकता है',
    'profile.expertChatStarted': 'विशेषज्ञ चैट शुरू',
    'profile.redirectingToExpert': 'विशेषज्ञ परामर्श के लिए पुनर्निर्देशित कर रहा है...',
    'profile.credits': 'क्रेडिट',
    'profile.noAchievements': 'अभी तक कोई उपलब्धि नहीं',
    'profile.keepParticipating': 'उपलब्धियां कमाने के लिए भाग लेते रहें!',

    // Expert Consultation
    'expert.title': 'विशेषज्ञ परामर्श',
    'expert.availableExperts': 'उपलब्ध विशेषज्ञ',
    'expert.selectExpert': 'परामर्श शुरू करने के लिए विशेषज्ञ चुनें (सत्र के लिए 50 AgriCreds)',
    'expert.online': 'ऑनलाइन',
    'expert.offline': 'ऑफलाइन',
    'expert.connect': 'कनेक्ट करें',
    'expert.connecting': 'कनेक्ट हो रहा है...',
    'expert.connected': 'कनेक्ट हो गया',
    'expert.sessionStarted': 'विशेषज्ञ परामर्श सत्र शुरू हो गया',
    'expert.connectionFailed': 'कनेक्शन विफल',
    'expert.tryAgain': 'कृपया पुनः प्रयास करें',
    'expert.disconnect': 'डिस्कनेक्ट करें',
    'expert.disconnected': 'डिस्कनेक्ट हो गया',
    'expert.sessionEnded': 'विशेषज्ञ परामर्श सत्र समाप्त हो गया',
    'expert.sessionTime': 'सत्र',
    'expert.typing': 'विशेषज्ञ टाइप कर रहा है...',
    'expert.typeMessage': 'अपना संदेश लिखें...',
    'expert.loginRequired': 'लॉगिन आवश्यक',
    'expert.pleaseLogin': 'विशेषज्ञों से बात करने के लिए कृपया लॉगिन करें',

    // Expert Chat Navigation
    'expertChat.title': 'विशेषज्ञ चैट परामर्श',
    'expertChat.description': 'कृषि विशेषज्ञों से चैट करें',
    'expertChat.requiresCredits': '50 AgriCreds की आवश्यकता है',
    'expertChat.availableCredits': 'उपलब्ध क्रेडिट',
    'expertChat.insufficientCredits': 'अपर्याप्त क्रेडिट',
    'expertChat.redirectingToCredits': 'AgriCreds पर पुनर्निर्देशित कर रहा है...',
    'expertChat.expertInfo': 'विशेषज्ञ जानकारी',
    'expertChat.costInfo': 'लागत जानकारी',

    // Common
    'common.now': 'अभी',
    'common.view': 'देखें',
    'common.edit': 'संपादित करें',
    'common.delete': 'हटाएं',
    'common.save': 'सहेजें',
    'common.cancel': 'रद्द करें',
    'common.ok': 'ठीक है',
    'common.yes': 'हाँ',
    'common.no': 'नहीं',
    'common.loading': 'लोड हो रहा है...',
    'common.error': 'त्रुटि',
    'common.success': 'सफल',
    'common.warning': 'चेतावनी',
    'common.info': 'जानकारी',
  },
  english: {
    // Header
    'header.agrisathi': 'AgriSaathi',
    'header.language.hindi': 'हिं',
    'header.language.english': 'EN',

    // Navigation
    'nav.home': 'Home',
    'nav.scan': 'Scan',
    'nav.community': 'Community',
    'nav.chat': 'Chat',
    'nav.wallet': 'Wallet',
    'nav.profile': 'Profile',

    // Dashboard
    'dashboard.welcome': 'Welcome, Farmer Brother!',
    'dashboard.subtitle': 'Better farming with modern technology',
    'dashboard.quickActions': 'Quick Actions',
    'dashboard.weather': "Today's Weather",
    'dashboard.cropRecommendations': 'Crop Recommendations',

    // Quick Actions
    'quickActions.scanCrop': 'Scan Crop',
    'quickActions.scanDescription': 'Disease Detection',
    'quickActions.voiceAsk': 'Ask by Voice',
    'quickActions.voiceDescription': 'Voice Assistant',
    'quickActions.expertChat': 'Expert Chat',
    'quickActions.expertDescription': 'Get instant advice',
    'quickActions.weather': 'Weather Info',
    'quickActions.weatherDescription': "Today's forecast",
    'quickActions.agriCreds': 'AgriCreds',
    'quickActions.earnMore': 'Earn more by contributing to the community!',

    // Weather
    'weather.today': "Today's Weather",
    'weather.humidity': 'Humidity',
    'weather.wind': 'Wind',
    'weather.uvIndex': 'UV Index',
    'weather.rainChance': 'Rain Chance',

    // Crop Recommendations
    'crops.recommendations': 'Crop Recommendations',
    'crops.season': 'Season',
    'crops.profitability': 'Profitability',
    'crops.high': 'High',
    'crops.medium': 'Medium',
    'crops.low': 'Low',
    'crops.yield': 'Yield',
    'crops.sowing': 'Sowing',
    'crops.marketRate': 'Market Rate',
    'crops.viewDetails': 'View Details',
    'crops.alerts': 'Alerts',

    // Crops
    'crops.tomato': 'Tomato',
    'crops.wheat': 'Wheat',
    'crops.season.rabi': 'Rabi',
    'crops.season.kharif': 'Kharif',
    'crops.profitability.high': 'High',
    'crops.profitability.medium': 'Medium',
    'crops.profitability.low': 'Low',
    'crops.yield.ton_per_hectare': 'ton/hectare',
    'crops.yield.kg_per_hectare': 'kilograms/hectare',
    'crops.market_unit.kg': 'kilogram',
    'crops.sowing.oct_nov': 'October-November',
    'crops.sowing.nov_dec': 'November-December',
    // Alerts
    'alerts.tomato_pest': 'Pest alert in tomato - treat immediately',
    'alerts.irrigation_needed': 'Irrigation needed - soil moisture is low',

    // Disease Detection
    'disease.title': 'Scan Crop',
    'disease.uploadPhoto': 'Upload Crop Photo',
    'disease.uploadDescription': 'Take clear photos of leaves, flowers, or fruits',
    'disease.gallery': 'Choose from Gallery',
    'disease.camera': 'Open Camera',
    'disease.uploadedPhoto': 'Uploaded Photo',
    'disease.startAnalysis': 'Start AI Analysis',
    'disease.analyzing': 'AI analysis in progress...',
    'disease.pleaseWait': 'Please wait',
    'disease.confidence': 'Confidence',
    'disease.severity': 'Severity',
    'disease.immediateActions': 'Immediate Actions',
    'disease.futurePrevention': 'Future Prevention',
    'disease.contactExpert': 'Contact Expert',
    'disease.buyMedicine': 'Buy Medicine',
    'disease.tips': 'Tips for better results',
    'disease.tip1': 'Take photos in natural light',
    'disease.tip2': 'Focus closely on the leaf',
    'disease.tip3': 'Take clear and sharp photos',
    'disease.tip4': 'Take photos from multiple angles',
    'disease.selectCrop': 'Select crop type (optional)',
    'disease.autoDetect': 'Auto-detect',
    'disease.uploadError': 'Image processing failed',
    'disease.invalidFileType': 'Please select a valid image file',
    'disease.fileTooLarge': 'File size must be less than 10MB',
    'disease.imageUploaded': 'Image uploaded',
    'disease.imageReadyForAnalysis': 'Image is ready for analysis',
    'disease.supportedFormats': 'Supported: JPG, PNG, WebP (max 10MB)',
    'disease.cameraDescription': 'Take a straight photo',
    'disease.analysisComplete': 'Analysis complete',
    'disease.analysisError': 'Image analysis failed. Please try again.',
    'disease.recentAnalyses': 'Recent analyses',
    'disease.dragDropText': 'Drag and drop an image here, or click to browse',
    'disease.browseFiles': 'Browse Files',

    // Chat
    'chat.title': 'AI Chat Assistant',
    'chat.expertBanner': 'Need expert advice?',
    'chat.expertSubtitle': 'Talk to certified agricultural experts',
    'chat.call': 'Call',
    'chat.availableExperts': 'Available Experts',
    'chat.chat': 'Chat',
    'chat.nextAvailable': 'Next Available',
    'chat.voiceListening': 'Listening...',
    'chat.speakQuestion': 'Speak your question',
    'chat.writeQuestion': 'Write your question...',
    'chat.commonQuestions': 'Common Questions',
    'chat.weatherInfo': 'Weather Information',
    'chat.fertilizerAmount': 'Fertilizer Amount',
    'chat.seedTreatment': 'Seed Treatment',
    'chat.irrigationTime': 'Irrigation Time',
    'chat.placeholder': 'Type your message...',
    'chat.typing': 'Typing...',
    'chat.clear': 'Clear',
    'chat.cleared': 'Chat Cleared',
    'chat.startNewConversation': 'Start a new conversation',
    'chat.responseReceived': 'Response Received',
    'chat.usingRealData': 'Using real agricultural data',
    'chat.usingMockData': 'Using mock data',
    'chat.apiError': 'API Error',
    'chat.error': 'Failed to get response',

    // Community
    'community.title': 'Community Forum',
    'community.searchPosts': 'Search posts...',
    'community.post': 'Post',
    'community.newPost': 'Write New Post',
    'community.category': 'Category',
    'community.writeQuestion': 'Write your question or suggestion...',
    'community.addPhoto': 'Add Photo',
    'community.postNow': 'Post Now',
    'community.share': 'Share',
    'community.problem': 'Problem',
    'community.tips': 'Tips',
    'community.experience': 'Experience',
    'community.market': 'Market',

    // Community categories
    'community.category.problem': 'Problem',
    'community.category.tips': 'Tips',
    'community.category.experience': 'Experience',
    'community.category.market': 'Market',

    // Additional Community translations
    'community.allCategories': 'All Categories',
    'community.loadingPosts': 'Loading posts...',
    'community.noPosts': 'No posts found',
    'community.categoryNoPosts': 'category has no posts',
    'community.posting': 'Posting...',
    'common.refresh': 'Refresh',

    // Voice recognition translations
    'voice.listening': 'Listening...',
    'voice.speakNow': 'Speak your question',
    'voice.detected': 'Voice Detected',
    'voice.error': 'Voice Error',
    'voice.notSupported': 'Voice Not Supported',
    'voice.browserSupport': 'Your browser does not support speech recognition',
    'voice.startFailed': 'Failed to start voice recognition',
    'voice.noInput': 'No Input',
    'voice.inputReceived': 'Voice Input Received',

    // Profile
    'profile.title': 'My Profile',
    'profile.farmingInfo': 'Farming Information',
    'profile.landSize': 'Land Size',
    'profile.experience': 'Experience',
    'profile.memberSince': 'Member Since',
    'profile.language': 'Language',
    'profile.mainCrops': 'Main Crops',
    'profile.activityStats': 'Activity Statistics',
    'profile.postsShared': 'Posts Shared',
    'profile.helpfulAnswers': 'Helpful Answers',
    'profile.questionsAsked': 'Questions Asked',
    'profile.creditsEarned': 'Credits Earned',

    // Wallet
    'wallet.title': 'Wallet',
    'wallet.connect': 'Connect Wallet',
    'wallet.disconnect': 'Disconnect Wallet',
    'wallet.overview': 'Overview',
    'wallet.send': 'Send',
    'wallet.buy': 'Buy',
    'wallet.sell': 'Sell',
    'wallet.history': 'History',
    'wallet.balance': 'Balance',
    'wallet.address': 'Wallet Address',
    'wallet.copied': 'Copied',
    'wallet.addressCopied': 'Address copied to clipboard',
    'wallet.sendAgriCreds': 'Send AgriCreds',
    'wallet.buyAgriCreds': 'Buy AgriCreds',
    'wallet.sellAgriCreds': 'Sell AgriCreds',
    'wallet.recipientAddress': 'Recipient Address',
    'wallet.amount': 'Amount',
    'wallet.numberOfAgriCreds': 'Number of AgriCreds',
    'wallet.ethRequired': 'ETH Required',
    'wallet.ethReceived': 'ETH Received',
    'wallet.transactionHistory': 'Transaction History',
    'wallet.prices': 'Prices',
    'wallet.security': 'Security',
    'wallet.walletSecure': 'Wallet is secure',
    'wallet.metamaskNotFound': 'MetaMask not found',
    'wallet.installMetamask': 'Please install MetaMask and refresh the page',
    'wallet.walletConnected': 'Wallet Connected',
    'wallet.walletConnectedSuccess': 'Your MetaMask wallet has been connected successfully',
    'wallet.connectionFailed': 'Connection Failed',
    'wallet.walletDisconnected': 'Wallet Disconnected',
    'wallet.walletDisconnectedSuccess': 'Your wallet has been disconnected',
    'wallet.insufficientBalance': 'Insufficient Balance',
    'wallet.notEnoughAgriCreds': 'You don\'t have enough AgriCreds',
    'wallet.insufficientEth': 'Insufficient ETH',
    'wallet.needEth': 'You need {amount} ETH',
    'wallet.agriCredsSent': 'AgriCreds Sent',
    'wallet.agriCredsSentSuccess': '{amount} AgriCreds sent successfully',
    'wallet.agriCredsPurchased': 'AgriCreds Purchased',
    'wallet.agriCredsPurchasedSuccess': '{amount} AgriCreds purchased successfully',
    'wallet.agriCredsSold': 'AgriCreds Sold',
    'wallet.agriCredsSoldSuccess': '{amount} AgriCreds sold successfully',
    'wallet.transactionFailed': 'Transaction Failed',
    'wallet.purchaseFailed': 'Purchase Failed',
    'wallet.saleFailed': 'Sale Failed',
    'wallet.invalidAmount': 'Invalid Amount',
    'wallet.enterValidAmount': 'Please enter a valid amount',
    'wallet.invalidAddress': 'Invalid Address',
    'wallet.enterValidAddress': 'Please enter a valid Ethereum address',
    'wallet.walletNotConnected': 'Wallet not connected',
    'wallet.connectWalletFirst': 'Please connect your wallet first',
    'wallet.sending': 'Sending...',
    'wallet.buying': 'Buying...',
    'wallet.selling': 'Selling...',
    'wallet.connecting': 'Connecting...',
    'wallet.connectMetamask': 'Connect MetaMask',
    'wallet.manageAgriCreds': 'Connect with MetaMask to manage your AgriCreds',
    'profile.achievements': 'Achievements',
    'profile.settings': 'Settings',
    'profile.changeLanguage': 'Change Language',
    'profile.redeemCredits': 'Redeem AgriCreds',
    'profile.insufficientCredits': 'Insufficient Credits',
    'profile.need50Credits': 'You need at least 50 AgriCreds to chat with experts',
    'profile.expertChatStarted': 'Expert Chat Started',
    'profile.redirectingToExpert': 'Redirecting to expert consultation...',
    'profile.credits': 'Credits',
    'profile.noAchievements': 'No achievements yet',
    'profile.keepParticipating': 'Keep participating to earn achievements!',

    // Expert Consultation
    'expert.title': 'Expert Consultation',
    'expert.availableExperts': 'Available Experts',
    'expert.selectExpert': 'Select an expert to start consultation (50 AgriCreds per session)',
    'expert.online': 'Online',
    'expert.offline': 'Offline',
    'expert.connect': 'Connect',
    'expert.connecting': 'Connecting...',
    'expert.connected': 'Connected',
    'expert.sessionStarted': 'Expert consultation session started',
    'expert.connectionFailed': 'Connection Failed',
    'expert.tryAgain': 'Please try again',
    'expert.disconnect': 'Disconnect',
    'expert.disconnected': 'Disconnected',
    'expert.sessionEnded': 'Expert consultation session ended',
    'expert.sessionTime': 'Session',
    'expert.typing': 'Expert is typing...',
    'expert.typeMessage': 'Type your message...',
    'expert.loginRequired': 'Login Required',
    'expert.pleaseLogin': 'Please login to chat with experts',

    // Expert Chat Navigation
    'expertChat.title': 'Expert Chat Consultation',
    'expertChat.description': 'Chat with agricultural experts',
    'expertChat.requiresCredits': 'Requires 50 AgriCreds',
    'expertChat.availableCredits': 'Available Credits',
    'expertChat.insufficientCredits': 'Insufficient Credits',
    'expertChat.redirectingToCredits': 'Redirecting to AgriCreds...',
    'expertChat.expertInfo': 'Expert Information',
    'expertChat.costInfo': 'Cost Information',

    // Common
    'common.now': 'Now',
    'common.view': 'View',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.ok': 'OK',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.warning': 'Warning',
    'common.info': 'Info',
  }
};

const LANGUAGE_STORAGE_KEY = 'anna-mitra-language';

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('hindi');

  // On mount, read language from localStorage
  useEffect(() => {
    const stored = localStorage.getItem(LANGUAGE_STORAGE_KEY);
    if (stored === 'hindi' || stored === 'english') {
      setLanguageState(stored);
    }
  }, []);

  // When language changes, persist to localStorage
  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem(LANGUAGE_STORAGE_KEY, lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}; 